global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics-text
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'address-service'
  scheme: http
  enable_http2: false
  metrics_path: /metrics-text
  static_configs:
    - targets: ['host.docker.internal:5254']
- job_name: 'auth-service'
  scheme: http
  enable_http2: false
  metrics_path: /metrics-text
  static_configs:
    - targets: ['host.docker.internal:5074']
- job_name: 'basket-service'
  scheme: http
  enable_http2: false
  metrics_path: /metrics-text
  static_configs:
    - targets: ['host.docker.internal:5216']
- job_name: 'order-service'
  scheme: http
  enable_http2: false
  metrics_path: /metrics-text
  static_configs:
    - targets: ['host.docker.internal:5231']
- job_name: 'product-service'
  scheme: http
  enable_http2: false
  metrics_path: /metrics-text
  static_configs:
    - targets: ['host.docker.internal:5160']